import { useEffect, useState, type ReactNode } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { changeRole, getAdminDashboard, listAuditLogs, listEvents, listOrders, listTickets, listUsers, moderateEvent } from '../services/admin.service'
import type { AdminDashboard, AdminEvent, AdminOrder, AdminTicket, AdminUser, AuditLog, Page } from '../services/admin.service'

type Tab = 'overview' | 'users' | 'events' | 'orders' | 'tickets' | 'audit'
export function AdminDashboardPage() {
  const { accessToken } = useAuth(); const [tab, setTab] = useState<Tab>('overview'); const [search, setSearch] = useState(''); const [filter, setFilter] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [dashboard, setDashboard] = useState<AdminDashboard | null>(null); const [users, setUsers] = useState<Page<AdminUser> | null>(null); const [events, setEvents] = useState<Page<AdminEvent> | null>(null); const [orders, setOrders] = useState<Page<AdminOrder> | null>(null); const [tickets, setTickets] = useState<Page<AdminTicket> | null>(null); const [audit, setAudit] = useState<Page<AuditLog> | null>(null)
  async function load(nextTab = tab, nextPage = page): Promise<void> { if (!accessToken) return; setLoading(true); setError(''); const filterKey = nextTab === 'users' ? 'role' : nextTab === 'audit' ? 'action' : 'status'; const query = `page=${nextPage}&limit=20&search=${encodeURIComponent(search)}${filter ? `&${filterKey}=${encodeURIComponent(filter)}` : ''}`; try { if (nextTab === 'overview') setDashboard(await getAdminDashboard(accessToken)); if (nextTab === 'users') setUsers(await listUsers(accessToken, query)); if (nextTab === 'events') setEvents(await listEvents(accessToken, query)); if (nextTab === 'orders') setOrders(await listOrders(accessToken, query)); if (nextTab === 'tickets') setTickets(await listTickets(accessToken, query)); if (nextTab === 'audit') setAudit(await listAuditLogs(accessToken, query)) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to load admin data') } finally { setLoading(false) } }
  useEffect(() => { void load(tab, page) }, [accessToken, tab, page])
  async function updateRole(user: AdminUser): Promise<void> { if (!accessToken || !window.confirm(`Change ${user.name}'s role?`)) return; await changeRole(accessToken, user.id, user.role === 'organizer' ? 'attendee' : 'organizer'); await load('users') }
  async function updateEvent(event: AdminEvent, status: string): Promise<void> { if (!accessToken || !window.confirm(`Change ${event.title} to ${status}?`)) return; await moderateEvent(accessToken, event.id, status); await load('events') }
  const tabs: Array<[Tab, string]> = [['overview', 'Overview'], ['users', 'Users'], ['events', 'Events'], ['orders', 'Orders'], ['tickets', 'Tickets'], ['audit', 'Audit logs']]; const currentPage = tab === 'users' ? users?.pagination : tab === 'events' ? events?.pagination : tab === 'orders' ? orders?.pagination : tab === 'tickets' ? tickets?.pagination : audit?.pagination
  const filterOptions = tab === 'users' ? [['', 'All roles'], ['attendee', 'Attendees'], ['organizer', 'Organizers'], ['admin', 'Admins']] : tab === 'events' ? [['', 'All statuses'], ['draft', 'Draft'], ['published', 'Published'], ['cancelled', 'Cancelled']] : tab === 'orders' ? [['', 'All statuses'], ['pending', 'Pending'], ['confirmed', 'Confirmed'], ['cancelled', 'Cancelled'], ['refunded', 'Refunded']] : tab === 'tickets' ? [['', 'All statuses'], ['active', 'Active'], ['used', 'Used'], ['cancelled', 'Cancelled']] : []
  return <section><div className="summary-line"><h2>Admin platform management</h2></div><nav className="admin-tabs">{tabs.map(([value, label]) => <button className={tab === value ? 'active' : ''} key={value} type="button" onClick={() => { setTab(value); setPage(1); setFilter('') }}>{label}</button>)}</nav>{tab !== 'overview' ? <div className="admin-filter"><input aria-label="Search admin records" placeholder="Search..." value={search} onChange={(event) => setSearch(event.target.value)} />{filterOptions.length ? <select aria-label="Filter admin records" value={filter} onChange={(event) => setFilter(event.target.value)}>{filterOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select> : null}<button type="button" onClick={() => { setPage(1); void load(tab, 1) }}>Search</button></div> : null}{error ? <p className="error" role="alert">{error}</p> : null}{loading ? <p>Loading...</p> : null}{tab === 'overview' && dashboard ? <Overview data={dashboard} /> : null}{tab === 'users' && users ? <Users data={users} onRole={updateRole} /> : null}{tab === 'events' && events ? <Events data={events} onStatus={updateEvent} /> : null}{tab === 'orders' && orders ? <Orders data={orders} /> : null}{tab === 'tickets' && tickets ? <Tickets data={tickets} /> : null}{tab === 'audit' && audit ? <Audit data={audit} /> : null}{currentPage ? <div className="pagination"><button type="button" disabled={currentPage.page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Page {currentPage.page} of {currentPage.totalPages || 1}</span><button type="button" disabled={currentPage.page >= currentPage.totalPages} onClick={() => setPage((value) => value + 1)}>Next</button></div> : null}</section>
}
function Overview({ data }: { data: AdminDashboard }) { const values = [['Users', data.users.total], ['Organizers', data.users.organizers], ['Attendees', data.users.attendees], ['Events', data.events.total], ['Published', data.events.published], ['Orders', data.orders.total], ['Tickets issued', data.tickets.issued], ['Checked in', data.tickets.checkedIn], ['Revenue', `$${data.confirmedRevenue}`]]; return <><div className="admin-metrics">{values.map(([label, value]) => <div className="dashboard-metric" key={String(label)}><span className="muted">{label}</span><strong>{value}</strong></div>)}</div><h3>Recent activity</h3>{data.recentActivity.map((item) => <p className="list-card" key={`${item.action}-${item.created_at}`}>{item.action} · {item.entity_type} · {new Date(item.created_at).toLocaleString()}</p>)}</> }
function Users({ data, onRole }: { data: Page<AdminUser>; onRole: (user: AdminUser) => void }) { return <DataTable headers={['Name', 'Email', 'Role', 'Events', 'Action']} rows={data.data.map((user) => [user.name, user.email, user.role, String(user.organizer_event_count ?? 0), user.role === 'admin' ? 'Protected' : <button type="button" onClick={() => void onRole(user)}>Change role</button>])} /> }
function Events({ data, onStatus }: { data: Page<AdminEvent>; onStatus: (event: AdminEvent, status: string) => void }) { return <DataTable headers={['Title', 'Organizer', 'Status', 'Action']} rows={data.data.map((event) => [event.title, event.organizer_name, event.status, event.status === 'draft' ? <button type="button" onClick={() => void onStatus(event, 'published')}>Publish</button> : event.status === 'published' ? <button type="button" onClick={() => void onStatus(event, 'cancelled')}>Cancel</button> : 'No action'])} /> }
function Orders({ data }: { data: Page<AdminOrder> }) { return <DataTable headers={['Order', 'Attendee', 'Event', 'Status', 'Payment', 'Total']} rows={data.data.map((order) => [order.order_number, order.attendee_email, order.event_title, order.status, order.payment_status, `${order.currency} ${order.total_amount}`])} /> }
function Tickets({ data }: { data: Page<AdminTicket> }) { return <DataTable headers={['Ticket', 'Attendee', 'Event', 'Status', 'Checked in']} rows={data.data.map((ticket) => [ticket.ticket_number, ticket.attendee_name, ticket.event_title, ticket.status, ticket.used_at ? new Date(ticket.used_at).toLocaleString() : '—'])} /> }
function Audit({ data }: { data: Page<AuditLog> }) { return <DataTable headers={['Action', 'Entity', 'Admin', 'When']} rows={data.data.map((item) => [item.action, `${item.entity_type} ${item.entity_id ?? ''}`, item.admin_name, new Date(item.created_at).toLocaleString()])} /> }
function DataTable({ headers, rows }: { headers: string[]; rows: Array<Array<string | number | ReactNode>> }) { return <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div> }